<?xml version="1.0" ?>
<!-- EventFlowXml, autogenerated Wed Mar 07 15:04:20 PST 2001 -->
<!DOCTYPE eventFlowXml [
        <!ELEMENT eventFlowXml (preMergeEvent, postMergeEvent, batchInfo, source, target?, da*, gsamd?, category*)>
        <!ELEMENT preMergeEvent (#PCDATA)>
        <!ELEMENT postMergeEvent (#PCDATA)>
        <!ELEMENT batchInfo (batchId, pageCount, pageNumber, displayName)>
        <!ATTLIST batchInfo
    localizationProfileId CDATA #REQUIRED
    processingMode (manual|automatic) "automatic">
        <!ELEMENT batchId (#PCDATA)>
        <!ELEMENT pageCount (#PCDATA)>
        <!ELEMENT pageNumber (#PCDATA)>
        <!ELEMENT displayName (#PCDATA)>
        <!ELEMENT da (dv*)>
        <!ATTLIST da
    name CDATA #REQUIRED>
        <!ELEMENT dv (#PCDATA)>
        <!ELEMENT source (locale, charset, da*)>
        <!ATTLIST source
    name CDATA #REQUIRED
    type (fs|db|cms) #REQUIRED
    fileProfileId CDATA "0"
    formatType CDATA "html">
        <!ELEMENT locale (#PCDATA)>
        <!ELEMENT charset (#PCDATA)>
        <!ELEMENT target (locale, charset, da*)>
        <!ATTLIST target
    name CDATA #REQUIRED
    databaseMode (preview|final) "final"
    previewUrl (true|false) "false">
        <!ELEMENT gsamd (da*)>
        <!ELEMENT category (da*)>
        <!ATTLIST category
    name CDATA #REQUIRED>
]>
<eventFlowXml>
    <preMergeEvent>Diplomat::PrsXmlTranslatedEvent</preMergeEvent>
    <postMergeEvent>Diplomat::DatabaseMergedEvent</postMergeEvent>
    <batchInfo localizationProfileId="1" processingMode="automatic">
        <batchId>984006259421</batchId>
        <pageCount>1</pageCount>
        <pageNumber>1</pageNumber>
        <displayName>Jim&apos;s Import test</displayName>
    </batchInfo>
    <source name="FileSourceAdapter" type="fs">
        <locale>en_US</locale>
        <charset>ISO-8859-1</charset>
    </source>
    <target name="FileTargetAdapter" databaseMode="final" previewUrl="false">
        <locale>Unknown</locale>
        <charset>Unknown</charset>
    </target>
</eventFlowXml>
