=== tilde-nlp/GlobalSight/main6/diplomat/install/doc/paginatedResultSetXml.dtd
<!-- edited with XML Spy v3.0 NT (http://www.xmlspy.com) by David McLeod (Global Sight) -->
<!-- Every paginatedResultSetXml consists of one or more record elements -->
<!-- PaginatedResultSetXml attributes are
	version: the version of the DTD describing this xml
	id: the string "PRS" followed by the creation timestamp
	locale: source locale (e.g. "en_US") taken from l18n profile -->
<!ELEMENT paginatedResultSetXml (record+)>
<!ATTLIST paginatedResultSetXml
	version CDATA "1.0"
	id ID #REQUIRED
	locale CDATA #REQUIRED
>
<!-- Every record consists of zero or one acquisition Sql parameter string, -->
<!-- one or more columns AND zero or more contexts -->
<!-- Record attributes are
		recordProfileId: the record profile associated with the record
		sequenceNumber: unique record number within this file only
                        (always prefixed with "SN") -->
<!ELEMENT record (acqSqlParm?, column+, context*)>
<!ATTLIST record
	recordProfileId CDATA #REQUIRED
	sequenceNumber ID #REQUIRED
>
<!-- Every acquisition Sql parameter string contains arbitrary text -->
<!ELEMENT acqSqlParm (#PCDATA)>
<!-- Every column consists of zero or one label and exactly one content -->
<!-- Column attributes are
		name: the name of the column as defined in the result set
		tableName: the name of the table from which the column was selected
		dataType: the kind of text (i.e. "text", "html", "xml", etc.)
		ruleId: the id of the rule used to parse the text (usually xml only)
		contentMode: how the content is to be viewed by the browser
			"translatable" -> the content will be translated
			"contextual" -> the content will be viewed only
			"invisible" -> must be carried so it can be saved later -->
<!ELEMENT column (label?, content)>
<!ATTLIST column
	name CDATA "unknown"
	tableName CDATA "unknown"
	dataType CDATA "text"
	ruleId CDATA "0"
	contentMode (translatable | contextual | invisible) "translatable"
>
<!-- Every context consists of zero or more columnHeaders and one or more rows -->
<!-- Context attributes are
		numRows: the number of rows of context
		numCols: the number of columns of context in each row -->
<!ELEMENT context (columnHeader*, row+)>
<!ATTLIST context
	numRows CDATA #REQUIRED
	numCols CDATA #REQUIRED
>
<!-- Every columnHeader contains arbitrary text -->
<!ELEMENT columnHeader (#PCDATA)>
<!-- Every (context) row consists of zero or one label, and one or more columns -->
<!ELEMENT row (label?, column+)>
<!-- Every label contains arbitrary text -->
<!ELEMENT label (#PCDATA)>
<!-- Every content contains arbitrary text -->
<!ELEMENT content (#PCDATA)>

=== tilde-nlp/GlobalSight/main6/diplomat/install/doc/paginatedResultSetXml.xml
<?xml version="1.0"?>
<!DOCTYPE paginatedResultSetXml SYSTEM "paginatedResultSetXml.dtd">
<paginatedResultSetXml version="1.0" id="PRS98450293490" locale="en_US">
	<record recordProfileId="rpid10249" sequenceNumber="SN1">
		<column name="PRODUCT_ID" tableName="PRODUCTS" dataType="text" ruleId="0" contentMode="contextual">
			<label>Product Id</label>
			<content>12345</content>
		</column>
		<column name="DESCRIPTION" tableName="PRODUCTS" dataType="text" ruleId="0" contentMode="translatable">
			<label>Description</label>
			<content>This is a product description that needs to be translated.</content>
		</column>
		<column name="ALT_DESCRIPTION" tableName="PROD_2" dataType="html" ruleId="0" contentMode="translatable">
			<label>Alternate Description</label>
			<content>&lt;b&gt;&lt;I&gt;This is some partially-escaped html stuff that needs to be translated.&lt;/I&gt;&lt;/b&gt;</content>
		</column>
		<context numRows="1" numCols="3">
			<columnHeader>Customer Header1</columnHeader>
			<columnHeader>Customer Header2</columnHeader>
			<columnHeader>Customer Header3</columnHeader>
			<row>
				<column contentMode="contextual">
					<content>Content for column 1</content>
				</column>
				<column contentMode="contextual">
					<content>Content for column 2</content>
				</column>
				<column contentMode="contextual">
					<content>Content for column 3</content>
				</column>
			</row>
		</context>
	</record>
</paginatedResultSetXml>
